#!/bin/sh
module="reminder"
device="reminder"
mode="664"

# remove stale nodes
rm -f /dev/${device}? 

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod ./$module.ko numminors=4 || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

#echo $major
mknod /dev/${device}0 c $major 0

ln -sf ${device}0  /dev/${device}

# give appropriate group/permissions
chmod $mode  /dev/${device}[0-3]
